---
name: Build_Docker
on:
  push:
    pull_request:
      branches: ["master"]

jobs:
  buiddocker:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: |
          docker build -f Dockerfile -t bernanoria/sabescomotedicen:$GITHUB_RUN_ID .