---
name: Release_Tag_Docker
on:
  push:
    tags:
      - "**"

jobs:
  releaase-tag:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332    # v4.1.7

      - env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          export TAG=$(echo $GITHUB_REF | cut -f3 -d/)
          docker login -u bernanoria -p $DOCKER_PASS
          docker build -f Dockerfile -t bernanoria/sabescomotedicen:$TAG .
          docker push bernanoria/sabescomotedicen:$TAG
  
  promote:
    runs-on: ubuntu-latest
    environment: production
    needs: releaase-tag
    permissions:
      contents: write
    steps:
      - name: checkout-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332    # v4.1.7

      - run: |
          export TAG=$(echo $GITHUB_REF | cut -f3 -d/)
          sed -i "s|\(image: .*:\).*|\1${TAG}|" k8s/deployment.yml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add k8s/deployment.yml
          git commit -m "Release version $TAG"
          git push