---
name: Release_Tag_Docker
on:
  push:
    branches: ["master"]

jobs:
  releaase-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332    # v4.1.7

      - env:
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: |
          export TAG=$(echo $GITHUB_REF | cut -f3 -d/)
          docker login -u bernanoria -p $DOCKER_PASS
          docker build -f Dockerfile -t bernanoria/sabescomotedicen:$TAG .
          docker push bernanoria/sabescomotedicen:$TAG
  
  promote-prod:
    runs-on: ubuntu-latest
    needs: releaase-version
    environment: production
    steps:
      - name: Promote version
        run: |
          echo "Promoting version to production"